import { readFile, realpath, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { atomicWrite, containedFile } from './files';
import { Conflict } from './comments';
import { renderOnce } from './render';
import { RenderFailure } from './render-error';
import type { SourceOverride } from './source-overrides';
import { HistoryError, sha256, snapshotDigest, summarize, type HistoryStore, type HistoryVersion, type Snapshot } from './history';
import { blockText, comparedLength, compareBlocks, describeBlock, excerpt, isBlockSource, restoreBlockSource, RestoreRefusal, snapshotBlocks, type SnapshotBlocks } from './history-blocks';
import type { BlockHistory, HistoryComparison, HistoryFileChange, RestoreResult, RestoreScope } from '../shared/history';
import type { BlockInfo } from '../shared/types';

export { RestoreRefusal } from './history-blocks';

const textMap = (snapshot: Snapshot) => new Map([...snapshot.text].map(([path, file]) => [path, file.content]));
const blockFiles = (files: Map<string, string>) => new Map([...files].filter(([path]) => isBlockSource(path)));

async function versionBlocks(store: HistoryStore, id: string, record: HistoryVersion, current: Snapshot) {
  const files = new Map<string, string>();
  for (const [path, file] of Object.entries(record.files)) {
    if (!isBlockSource(path)) continue;
    const now = current.text.get(path);
    files.set(path, now?.hash === file.hash ? now.content : await store.readBlob(id, file.hash));
  }
  return snapshotBlocks(files);
}

/** What changed between a recorded version and the current text sources. */
export async function compareVersion(store: HistoryStore, id: string, versionId: string): Promise<HistoryComparison> {
  const record = await store.version(id, versionId);
  const current = await store.snapshot(id);
  const files: HistoryFileChange[] = [];
  for (const path of [...new Set([...Object.keys(record.files), ...current.text.keys()])].sort()) {
    const before = record.files[path]?.hash, after = current.text.get(path)?.hash;
    if (before === after) continue;
    files.push({ path, status: !before ? 'added' : !after ? 'removed' : 'modified' });
  }
  const blocks = files.some(file => isBlockSource(file.path))
    ? compareBlocks(await versionBlocks(store, id, record, current), snapshotBlocks(blockFiles(textMap(current))))
    : [];
  return { documentId: id, version: summarize(record), base: snapshotDigest(current.text), blocks, files, identical: !files.length };
}

function offsetAt(source: string, line: number, column: number) {
  let offset = 0;
  for (let index = 1; index < line; index++) {
    const next = source.indexOf('\n', offset);
    if (next < 0) return -1;
    offset = next + 1;
  }
  return offset + column - 1;
}

/** Map a rendered block to the authored element with a literal ID that produces it. */
export function resolveSourceBlock(current: SnapshotBlocks, id: string, documentId: string, block?: BlockInfo): { id: string; resolution: 'exact' | 'enclosing' } {
  const exact = current.byId.get(id);
  if (exact?.length === 1) return { id, resolution: 'exact' };
  if (exact && exact.length > 1) throw new RestoreRefusal(`The ID “${id}” appears more than once in the source, so its history is ambiguous. Use whole-version restore instead.`);
  const prefix = `documents/${documentId}/`;
  if (block?.source?.file.startsWith(prefix)) {
    const file = block.source.file.slice(prefix.length);
    const index = current.indexes.get(file);
    const offset = index ? offsetAt(index.source, block.source.line, block.source.column) : -1;
    const enclosing = index?.blocks.filter(item => item.start <= offset && offset < item.end).sort((a, b) => (a.end - a.start) - (b.end - b.start))[0];
    if (enclosing && current.byId.get(enclosing.id)?.length === 1) return { id: enclosing.id, resolution: 'enclosing' };
  }
  // Composite blocks derive child IDs such as `<id>-heading` from their own literal ID.
  const owner = [...current.byId.keys()].filter(key => id.startsWith(`${key}-`) && current.byId.get(key)!.length === 1).sort((a, b) => b.length - a.length)[0];
  if (owner) return { id: owner, resolution: 'enclosing' };
  throw new RestoreRefusal('This item’s ID is generated by code, so it has no history of its own. Restore a whole version instead, or ask your agent to give it a literal ID.');
}

/** Earlier distinct forms of one authored block, newest first. */
export async function blockHistory(store: HistoryStore, documentId: string, requested: string, rendered?: BlockInfo): Promise<BlockHistory> {
  const current = await store.snapshot(documentId);
  const blocks = snapshotBlocks(blockFiles(textMap(current)));
  const { id, resolution } = resolveSourceBlock(blocks, requested, documentId, rendered);
  const now = blocks.byId.get(id)![0];
  const container = now.children.length > 0;
  // Each distinct wording is shown once, dated by the version that began its most recent run.
  const runs: { key: string; record: HistoryVersion; source: string; container: boolean }[] = [];
  for (const record of (await store.versions(documentId)).slice(-400)) {
    const file = record.files[now.file];
    if (!file) continue;
    let source: string;
    try { source = await store.readBlob(documentId, file.hash); } catch { continue; }
    const found = snapshotBlocks(new Map([[now.file, source]])).byId.get(id);
    if (found?.length !== 1) continue;
    const key = found[0].source.replace(/\s+/g, ' ').trim();
    if (runs.at(-1)?.key !== key) runs.push({ key, record, source: found[0].source, container: found[0].children.length > 0 });
  }
  const currentKey = now.source.replace(/\s+/g, ' ').trim();
  const seen = new Set([currentKey]);
  const entries: BlockHistory['entries'] = [];
  for (const run of runs.reverse()) {
    if (seen.has(run.key) || entries.length >= 60) continue;
    seen.add(run.key);
    entries.push({ version: summarize(run.record), text: excerpt(blockText(now.file, run.source, false), comparedLength), container: run.container });
  }
  return { documentId, requested, id, resolution, kind: now.kind, ...describeBlock(now), container, current: excerpt(blockText(now.file, now.source, false), comparedLength), base: snapshotDigest(current.text), entries };
}

export interface RestoreOptions {
  scope: RestoreScope;
  blockId?: string;
  /** The current-source digest the user reviewed; a mismatch refuses the restore. */
  base?: string;
  /** Record outstanding outside changes and the restored state; the server routes this through its recorder. */
  record?: (origin: 'external' | 'restore', extra?: Pick<HistoryVersion, 'restore'>) => Promise<HistoryVersion | null>;
  /** Called with each written file, so a running service can refresh immediately. */
  written?: (path: string) => void;
  timeoutMs?: number;
}

/**
 * Restore one block, one section, or a whole version. The candidate is rendered before
 * anything is written, and the prior state is recorded first, so every restore can itself be undone.
 */
export async function restoreVersion(store: HistoryStore, id: string, versionId: string, options: RestoreOptions): Promise<RestoreResult> {
  const { scope } = options;
  if (!['version', 'block', 'section'].includes(scope)) throw new HistoryError('Choose a version, block, or section to restore.');
  if (scope !== 'version' && (typeof options.blockId !== 'string' || !options.blockId)) throw new HistoryError('Choose the block to restore.');
  const record = await store.version(id, versionId);
  const capture = options.record ?? (async (origin, extra) => (await store.capture(id, origin, extra)).version);
  // Keep the state being replaced as its own version before changing anything.
  await capture('external');
  const latest = (await store.versions(id)).at(-1);
  if (!latest) throw new HistoryError('This document has no recorded history yet.', 409);
  const current = await store.snapshot(id);
  if (options.base !== undefined && options.base !== snapshotDigest(current.text)) throw new Conflict('The document changed after you opened this version. Review the latest changes and try again.');
  const changes = new Map<string, string>();
  if (scope === 'version') {
    const files = await store.versionFiles(id, record);
    for (const [path, contents] of files) if (current.text.get(path)?.content !== contents) changes.set(path, contents);
    if (!changes.size) throw new RestoreRefusal('The current text already matches that version.');
  } else {
    const before = await versionBlocks(store, id, record, current);
    if (before.errors.length && !before.byId.has(options.blockId!)) throw new RestoreRefusal(`That version's source has a syntax error (${before.errors[0]}), so its blocks cannot be identified. Restore the whole version instead.`);
    const now = snapshotBlocks(blockFiles(textMap(current)));
    if (now.errors.length) throw new RestoreRefusal(`The current source cannot be parsed (${now.errors[0]}). Restore the whole version instead.`);
    const { file, contents } = restoreBlockSource(before, now, options.blockId!, scope);
    changes.set(file, contents);
  }
  const folder = await store.folder(id);
  const targets = new Map<string, { path: string; contents: string; previous?: string }>();
  for (const [file, contents] of changes) {
    const path = resolve(folder, file);
    const existing = current.text.get(file);
    if (existing) await containedFile(folder, path);
    targets.set(file, { path, contents, previous: existing?.content });
  }
  // Render the candidate through isolated source overrides; nothing is written if it fails.
  const overrides: SourceOverride[] = [];
  let checkable = true;
  for (const target of targets.values()) {
    if (target.previous === undefined) { checkable = false; continue; }
    if (isBlockSource(target.path)) overrides.push({ file: await realpath(target.path), contents: target.contents, originalDigest: sha256(target.previous), replacements: [], optional: true });
  }
  const verify = async (sources?: SourceOverride[]) => {
    try { const result = await renderOnce(store.root, id, options.timeoutMs ?? 60_000, sources); await rm(result.directory, { recursive: true, force: true }); }
    catch (error) {
      const detail = error instanceof RenderFailure || error instanceof Error ? error.message : String(error);
      throw new RestoreRefusal(`The restored ${scope === 'version' ? 'version' : scope} does not render, so the document was not changed. ${detail.split('\n')[0].slice(0, 400)}`);
    }
  };
  if (checkable && overrides.length) await verify(overrides);
  const write = async (target: { path: string; contents: string }, expected: string | undefined) => {
    const now = await readFile(target.path, 'utf8').catch(error => { if (error.code === 'ENOENT') return undefined; throw error; });
    if (now !== expected) throw new Conflict('The source changed while restoring. Nothing else was changed; review the latest version and try again.');
    await atomicWrite(target.path, target.contents);
    options.written?.(target.path);
  };
  const written: { path: string; previous?: string }[] = [];
  try {
    for (const target of targets.values()) { await write(target, target.previous); written.push(target); }
    // Restoring a file that no longer exists cannot be checked in isolation; check it in place.
    if (!checkable) await verify();
  } catch (error) {
    for (const item of written.reverse()) {
      if (item.previous === undefined) await rm(item.path, { force: true });
      else await atomicWrite(item.path, item.previous);
      options.written?.(item.path);
    }
    throw error;
  }
  const version = await capture('restore', { restore: { from: versionId, scope, ...(options.blockId && scope !== 'version' ? { blockId: options.blockId } : {}) } });
  return { documentId: id, scope, ...(scope !== 'version' ? { blockId: options.blockId } : {}), version: version ? summarize(version) : null, previous: latest.id, files: [...targets.keys()] };
}
