import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { promisify } from 'node:util';
import { execFile } from 'node:child_process';
import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { fixture, projectRoot, until, source } from './helpers';
import type { DocumentState } from '../src/shared/types';

// This loop renders many successive edits; each transition still has its own bounded wait.
test('local HTTP loop: discovery, watch, errors, exact export, and request boundaries', { timeout: 120_000 }, async () => {
  const f = await fixture();
  const child = spawn(process.execPath, ['--import', 'tsx', resolve(projectRoot, 'src/server/index.ts')], { cwd: f.root, env: { ...process.env, OPENDOC_PORT: '0' }, stdio: ['ignore', 'pipe', 'pipe'] });
  let logs = ''; child.stdout.on('data', d => logs += d); child.stderr.on('data', d => logs += d);
  try {
    let connection: { origin: string; token: string } | undefined;
    await until(async () => { try { connection = JSON.parse(await readFile(resolve(f.root, '.opendoc/server.json'), 'utf8')); return true; } catch { if (child.exitCode !== null) throw new Error(logs); return false; } });
    const { origin, token } = connection!;
    const list = () => fetch(`${origin}/api/documents`).then(r => r.json()) as Promise<DocumentState[]>;
    const state = async () => (await list()).find(d => d.id === 'proof')!;
    await until(async () => (await state())?.status === 'ready');
    const initial = await state();
    const hash = initial.artifact!.hash;
    const summary = (await fetch(`${origin}/api/documents?view=summary`).then(r => r.json()))[0];
    const detail = await fetch(`${origin}/api/documents/proof`).then(r => r.json());
    assert.equal(summary.artifact.hash, detail.artifact.hash);
    assert.equal(summary.revision, detail.revision);
    assert.equal(summary.artifact.pages.length, detail.artifact.pages.length);
    assert.ok(!('blocks' in summary.artifact) && !('textTargets' in summary.artifact));
    assert.ok(summary.artifact.pages.every((page: object) => !('fragments' in page)));
    assert.ok(Object.keys(detail.artifact.blocks).length > 0);
    assert.equal((await fetch(`${origin}/api/documents/missing`)).status, 404);
    const previewResponse = await fetch(`${origin}/api/documents/proof/pdf?hash=${hash}`);
    const preview = new Uint8Array(await previewResponse.arrayBuffer());
    const headers = { 'Content-Type': 'application/json', 'X-OpenDoc-Token': token, Origin: origin };
    const exported = await fetch(`${origin}/api/documents/proof/export`, { method: 'POST', headers, body: JSON.stringify({ hash }) });
    assert.equal(exported.status, 200);
    const bytes = new Uint8Array(await exported.arrayBuffer());
    assert.deepEqual(bytes, preview);
    assert.deepEqual(new Uint8Array(await readFile(resolve(f.root, 'output/proof.pdf'))), preview);
    assert.equal(createHash('sha256').update(bytes).digest('hex'), hash);
    await promisify(execFile)(process.execPath, ['--import', 'tsx', resolve(projectRoot, 'src/server/export.ts'), '--', 'proof'], { cwd: f.root });
    assert.deepEqual(new Uint8Array(await readFile(resolve(f.root, 'output/proof.pdf'))), preview, 'CLI must reuse the current preview bytes');
    const denied = await fetch(`${origin}/api/documents/proof/export`, { method: 'POST', headers: { ...headers, Origin: 'https://example.com' }, body: JSON.stringify({ hash }) });
    assert.equal(denied.status, 403);
    assert.equal((await fetch(`${origin}/api/context`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status, 403);
    assert.equal((await fetch(`${origin}/api/documents/%2e%2e%2fsecret/pdf?hash=x`)).status, 404);
    assert.equal(initial.projectId, 'test-project');
    const projectWrite = (path: string, method: string, body?: unknown, customHeaders = headers) => fetch(`${origin}${path}`, { method, headers: customHeaders, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    assert.equal((await projectWrite('/api/projects', 'POST', { name: 'No token' }, { 'Content-Type': 'application/json' } as typeof headers)).status, 403);
    assert.equal((await projectWrite('/api/projects', 'POST', { name: 'Wrong origin' }, { ...headers, Origin: 'https://example.com' })).status, 403);
    assert.equal((await projectWrite('/api/documents', 'POST', { id: 'no-project', title: 'No project', starter: 'report' })).status, 400);
    const newProject = await projectWrite('/api/projects', 'POST', { id: 'http-project', name: 'HTTP project', defaultTheme: 'civic-spectrum' });
    assert.equal(newProject.status, 201);
    assert.equal((await projectWrite('/api/projects/http-project', 'PATCH', { name: 'Renamed HTTP project' })).status, 200);
    assert.equal((await projectWrite('/api/context', 'POST', { documentId: null, blockId: null, page: 1, projectId: 'http-project' })).status, 200);
    assert.equal(JSON.parse(await readFile(resolve(f.root, '.opendoc/current.json'), 'utf8')).project.name, 'Renamed HTTP project');
    assert.equal((await projectWrite('/api/documents/proof/project', 'PUT', { projectId: 'http-project' })).status, 200);
    assert.equal((await state()).projectId, 'http-project');
    assert.equal((await state()).artifact!.hash, hash);
    assert.equal((await projectWrite('/api/context', 'POST', { documentId: 'proof', blockId: null, page: 1 })).status, 200);
    assert.equal(JSON.parse(await readFile(resolve(f.root, '.opendoc/current.json'), 'utf8')).projectId, 'http-project');
    assert.equal((await projectWrite('/api/projects/http-project', 'DELETE')).status, 409);
    assert.equal((await projectWrite('/api/documents/proof/project', 'PUT', { projectId: 'test-project' })).status, 200);
    assert.equal((await projectWrite('/api/projects/http-project', 'DELETE')).status, 200);
    for (const [path, method] of [['/api/documents/proof', 'PATCH'], ['/api/documents/proof', 'DELETE'], ['/api/documents/proof/duplicate', 'POST'], ['/api/document-trash/00000000-0000-4000-8000-000000000000/restore', 'POST']]) {
      assert.equal((await projectWrite(path, method, { name: 'Denied' }, { 'Content-Type': 'application/json' } as typeof headers)).status, 403);
    }
    assert.equal((await projectWrite('/api/documents/proof', 'PATCH', { name: 'Library proof' })).status, 200);
    assert.equal((await state()).name, 'Library proof');
    assert.equal((await state()).artifact!.hash, hash);
    const copiedDocument = await projectWrite('/api/documents/proof/duplicate', 'POST');
    assert.equal(copiedDocument.status, 201);
    const copyId = (await copiedDocument.json()).id;
    await until(async () => (await list()).some(d => d.id === copyId && d.status === 'ready'));
    const removedDocument = await projectWrite(`/api/documents/${copyId}`, 'DELETE');
    assert.equal(removedDocument.status, 200);
    const restoreId = (await removedDocument.json()).restoreId;
    assert.ok(!(await list()).some(d => d.id === copyId));
    assert.equal((await projectWrite(`/api/document-trash/${restoreId}/restore`, 'POST')).status, 200);
    await until(async () => (await list()).some(d => d.id === copyId && d.status === 'ready' && d.name === 'Copy of Library proof'));
    assert.equal((await projectWrite(`/api/documents/${copyId}`, 'DELETE')).status, 200);
    const themeCatalog = await fetch(`${origin}/api/themes`).then(r => r.json());
    for (const id of ['neutral', 'civic-spectrum', 'field-manual', 'opendoc-neutral', 'mckinsey-consulting']) {
      assert.ok(themeCatalog.some((theme: { id: string }) => theme.id === id), `Theme ${id} is discoverable over HTTP.`);
    }
    assert.ok(themeCatalog.every((theme: { revision?: string; error?: string }) => theme.revision && !theme.error));
    const guide = await fetch(`${origin}/api/themes/civic-spectrum/guide`);
    assert.equal(guide.headers.get('cache-control'), 'no-store');
    assert.match((await guide.json()).markdown, /Civic Spectrum/);
    assert.equal((await projectWrite('/api/context', 'POST', { documentId: null, blockId: null, page: 1, themeId: 'civic-spectrum' })).status, 200);
    const themeContext = JSON.parse(await readFile(resolve(f.root, '.opendoc/current.json'), 'utf8'));
    assert.equal(themeContext.themeId, 'civic-spectrum');
    assert.equal(themeContext.theme.guide, 'themes/civic-spectrum/design.md');
    assert.ok(!JSON.stringify(themeContext).includes('## Composition'), 'Context points to the guide without embedding it.');
    assert.equal((await projectWrite('/api/context', 'POST', { documentId: null, blockId: null, page: 1, themeId: '../outside' })).status, 400);
    const catalog = await fetch(`${origin}/api/starters`).then(r => r.json());
    assert.ok(catalog.starters.some((starter: { id: string }) => starter.id === 'technical'));
    const creation = await fetch(`${origin}/api/documents`, { method: 'POST', headers, body: JSON.stringify({ projectId: 'test-project', title: 'HTTP creation proof', id: 'created-report', starter: 'report' }) });
    assert.equal(creation.status, 201);
    assert.equal((await creation.json()).id, 'created-report');
    await until(async () => (await list()).some(d => d.id === 'created-report' && d.status === 'ready'));
    const originalEntry = await readFile(resolve(f.root, 'documents/created-report/index.tsx'), 'utf8');
    const duplicate = await fetch(`${origin}/api/documents`, { method: 'POST', headers, body: JSON.stringify({ projectId: 'test-project', title: 'Do not overwrite', id: 'created-report', starter: 'article' }) });
    assert.equal(duplicate.status, 409);
    assert.equal(await readFile(resolve(f.root, 'documents/created-report/index.tsx'), 'utf8'), originalEntry);
    assert.equal((await fetch(`${origin}/api/documents`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: 'Unapproved write', starter: 'report' }) })).status, 403);
    const commented = await fetch(`${origin}/api/documents/proof/comments`, { method: 'POST', headers, body: JSON.stringify({ hash, blockId: 'target', text: 'Please clarify the example.' }) });
    assert.equal(commented.status, 200);
    await writeFile(f.entry, 'export default =');
    await until(async () => (await state()).status === 'error');
    assert.equal((await state()).artifact!.hash, hash);
    assert.equal((await fetch(`${origin}/api/documents/proof/export`, { method: 'POST', headers, body: JSON.stringify({ hash }) })).status, 409);
    await writeFile(f.entry, source().replace('Proof document', 'Revised title'));
    await until(async () => { const s = await state(); return s.status === 'ready' && s.artifact?.meta.title === 'Revised title'; });
    assert.equal((await fetch(`${origin}/api/documents/proof/comments`).then(r => r.json())).length, 1);
    const themeFile = resolve(f.root, 'themes/neutral/index.ts');
    const beforeTheme = (await state()).revision;
    await writeFile(themeFile, (await readFile(themeFile, 'utf8')).replace("accent: '#424242'", "accent: '#453784'"));
    await until(async () => { const s = await state(); return s.status === 'ready' && s.revision > beforeTheme; });
    const moduleFile = resolve(f.root, 'documents/proof/copy.ts');
    await writeFile(moduleFile, "export const words = 'Imported first version';");
    const asset = resolve(f.root, 'documents/proof/figure.svg');
    const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="120" height="50"><rect width="120" height="50" fill="#27644d"/></svg>';
    await writeFile(asset, svg);
    await writeFile(f.entry, `import {readFileSync} from 'node:fs'; import {resolve} from 'node:path'; import {Figure,Svg} from '../../src/document'; import {words} from './copy';\n` + source('<Paragraph id="imported">{words}</Paragraph><Figure id="figure" caption="Local asset"><Svg width={120} height={50} content={readFileSync(resolve(process.cwd(),"documents/proof/figure.svg"),"utf8")}/></Figure>'));
    await until(async () => { const s = await state(); return s.status === 'ready' && !!s.artifact?.blocks.imported; });
    await writeFile(moduleFile, "export const words = 'Imported revised version';");
    await until(async () => { const s = await state(); return s.status === 'ready' && s.artifact?.blocks.imported.text === 'Imported revised version'; });
    const beforeAsset = (await state()).artifact!.hash;
    await writeFile(asset, svg.replace('#27644d', '#453784'));
    await until(async () => { const s = await state(); return s.status === 'ready' && s.artifact!.hash !== beforeAsset; });
    const beforeMissing = (await state()).artifact!.hash;
    await rm(asset);
    await until(async () => (await state()).status === 'error');
    assert.match((await state()).error!, /ENOENT|no such file/);
    assert.equal((await state()).artifact!.hash, beforeMissing);
    await writeFile(asset, svg);
    await until(async () => (await state()).status === 'ready');
    const csv = resolve(f.root, 'documents/proof/measurements.csv');
    const modernModule = resolve(f.root, 'documents/proof/summary.mts');
    await writeFile(csv, 'sample,value\none,12');
    await writeFile(modernModule, "export const summary = 'First module summary';");
    await writeFile(f.entry, `import {readFileSync} from 'node:fs'; import {resolve} from 'node:path'; import {summary} from './summary.mts';\n` + source('<Paragraph id="csv">{readFileSync(resolve(process.cwd(),"documents/proof/measurements.csv"),"utf8")}</Paragraph><Paragraph id="module-summary">{summary}</Paragraph>'));
    await until(async () => { const s = await state(); return s.status === 'ready' && !!s.artifact?.blocks.csv; });
    await writeFile(csv, 'sample,value\none,24');
    await until(async () => { const s = await state(); return s.status === 'ready' && /24/.test(s.artifact?.blocks.csv.text ?? ''); });
    await writeFile(modernModule, "export const summary = 'Updated module summary';");
    await until(async () => { const s = await state(); return s.status === 'ready' && s.artifact?.blocks['module-summary'].text === 'Updated module summary'; });
    const newDir = resolve(f.root, 'documents/another-document');
    await mkdir(newDir); await writeFile(resolve(newDir, 'index.tsx'), source().replace('Proof document', 'Another document'));
    await until(async () => (await list()).some(d => d.id === 'another-document' && d.status === 'ready'));
    await rm(newDir, { recursive: true });
    await until(async () => !(await list()).some(d => d.id === 'another-document'));
  } finally {
    child.kill('SIGTERM');
    await Promise.race([new Promise(r => child.once('exit', r)), new Promise(r => setTimeout(r, 5000))]);
    if (child.exitCode === null) child.kill('SIGKILL');
    await f.cleanup();
  }
});
