import test from 'node:test';
import assert from 'node:assert/strict';
import { cp, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { renderOnce } from '../src/server/render';
import { TextEditService } from '../src/server/edits';
import { canCorrectComponent } from '../src/app/componentCorrection';
import type { TextTarget } from '../src/shared/selection';
import type { RenderArtifact } from '../src/shared/types';
import { fixture, projectRoot } from './helpers';

const capitals = /The theme sets this label in capitals/;
const templateLabel = /This label is generated by the template/;
const imagePlaceholder = /This placeholder is generated by the template. Ask your agent to add an image/;

async function templatesFixture() {
  const f = await fixture();
  await cp(resolve(projectRoot, 'templates'), resolve(f.root, 'templates'), { recursive: true });
  return f;
}

/** A synthetic document; `capitals` gives the theme capitalised eyebrows and running headers. */
const document = (imports: string, body: string, options: { capitals?: boolean } = {}) => `${imports}
import { neutral } from '../../themes';
const theme = ${options.capitals ? `{ ...neutral, runningHeader: true, design: { title: { uppercaseEyebrow: true }, furniture: { uppercaseHeader: true } } }` : 'neutral'};
export const meta = { title: 'Template labels', description: 'Synthetic template label fixture', theme: 'neutral' };
export default function Proof() { return ${body}; }`;

function targetsOf(artifact: RenderArtifact) {
  const targets = artifact.textTargets ?? [];
  const slot = (blockId: string, name: string) => {
    const found = targets.find(target => target.blockId === blockId && target.slot === name);
    assert.ok(found, `${blockId} ${name}`);
    return found;
  };
  return { targets, slot };
}
function editable(target: TextTarget, value: string) {
  assert.ok(canCorrectComponent(target), `${target.id} is editable`);
  const binding = target.runs.find(run => run.source)!.source!;
  assert.equal(binding.file, 'documents/proof/index.tsx', `${target.id} saves to the document's call site`);
  assert.equal(binding.value, value);
}
function readOnly(target: TextTarget, reason: RegExp) {
  assert.equal(canCorrectComponent(target), false, `${target.id} stays read-only`);
  assert.match(target.reason!, reason, target.id);
}
/** Replace a whole target's text through the reader's save path and return the saved source. */
async function save(root: string, artifact: RenderArtifact, target: TextTarget, replacement: string) {
  await new TextEditService(root).apply('proof', { targetId: target.id, start: 0, end: target.text.length, replacement, revision: 1, hash: artifact.hash }, { id: 'proof', status: 'ready', revision: 1, artifact });
  return readFile(resolve(root, 'documents/proof/index.tsx'), 'utf8');
}

test('report and brief labels edit at the call site, and say so when the theme capitalises them', async () => {
  const f = await templatesFixture();
  try {
    const report = (capitalsTheme: boolean) => document(`import { ConsultingReport } from '../../templates/consulting-report';`,
      `<ConsultingReport title="Quarterly operations" theme={theme} cover={false} label="Operations review" runningTitle="Operations"><></></ConsultingReport>`, { capitals: capitalsTheme });
    await writeFile(f.entry, report(true));
    let rendered = (await renderOnce(f.root, 'proof')).artifact;
    let { slot } = targetsOf(rendered);
    assert.equal(slot('report-label', 'label').text, 'OPERATIONS REVIEW');
    readOnly(slot('report-label', 'label'), capitals);

    await writeFile(f.entry, report(false));
    rendered = (await renderOnce(f.root, 'proof')).artifact;
    ({ slot } = targetsOf(rendered));
    editable(slot('report-label', 'label'), 'Operations review');
    const before = await readFile(f.entry, 'utf8');
    assert.equal(await save(f.root, rendered, slot('report-label', 'label'), 'Operations audit'), before.replace('label="Operations review"', 'label="Operations audit"'));

    const brief = (capitalsTheme: boolean) => document(`import { ExecutiveBrief } from '../../templates/executive-brief';`,
      `<ExecutiveBrief title="Brief" theme={theme} label="Board update" author="Strategy team" date="May 2026"><></></ExecutiveBrief>`, { capitals: capitalsTheme });
    await writeFile(f.entry, brief(true));
    rendered = (await renderOnce(f.root, 'proof')).artifact;
    ({ slot } = targetsOf(rendered));
    assert.equal(slot('brief-label', 'label').text, 'BOARD UPDATE');
    readOnly(slot('brief-label', 'label'), capitals);

    await writeFile(f.entry, brief(false));
    rendered = (await renderOnce(f.root, 'proof')).artifact;
    ({ slot } = targetsOf(rendered));
    editable(slot('brief-label', 'label'), 'Board update');
    const details = slot('brief-details', 'author');
    assert.deepEqual(details.runs.map(run => [details.text.slice(run.start, run.end), run.source?.value ?? run.reason?.split('.')[0]]),
      [['Strategy team', 'Strategy team'], [' · ', 'This part is generated by the component that draws it'], ['May 2026', 'May 2026']]);
  } finally { await f.cleanup(); }
});

test('image-story and company-profile defaults explain themselves, and supplied labels edit at the call site', async () => {
  const f = await templatesFixture();
  try {
    await writeFile(f.entry, document(`import { ImageStory, ImageStoryPage } from '../../templates/image-story';`,
      `<ImageStory title="Story" theme={theme}><ImageStoryPage id="first" theme={theme} title="First page" /><ImageStoryPage id="second" theme={theme} title="Second page" footer="Field notes" /></ImageStory>`));
    let rendered = (await renderOnce(f.root, 'proof')).artifact;
    assert.deepEqual(rendered.issues, []);
    let { slot } = targetsOf(rendered);
    assert.equal(slot('first-footer', 'footer').text, 'IMAGE STORY');
    readOnly(slot('first-footer', 'footer'), templateLabel);
    readOnly(slot('first-image', 'placeholder'), imagePlaceholder);
    editable(slot('second-footer', 'footer'), 'Field notes');
    let before = await readFile(f.entry, 'utf8');
    assert.equal(await save(f.root, rendered, slot('second-footer', 'footer'), 'Site notes'), before.replace('footer="Field notes"', 'footer="Site notes"'));

    const manifestFile = resolve(f.root, 'projects.json');
    await writeFile(manifestFile, JSON.stringify({ ...JSON.parse(await readFile(manifestFile, 'utf8')), formats: { proof: 'presentation' } }));
    await writeFile(f.entry, document(`import { CompanyProfile, ProfileImage, ProfileSlide } from '../../templates/company-profile';`,
      `<CompanyProfile title="Profile" theme={theme}><ProfileSlide id="slide" theme={theme} title="Places" footer="Northwind profile">
        <ProfileImage id="default-image" theme={theme} x={40} y={200} width={300} height={200} />
        <ProfileImage id="named-image" theme={theme} x={400} y={200} width={300} height={200} label="Harbour office" />
      </ProfileSlide><ProfileSlide id="plain" theme={theme} title="Plain" /></CompanyProfile>`));
    rendered = (await renderOnce(f.root, 'proof')).artifact;
    ({ slot } = targetsOf(rendered));
    assert.equal(slot('default-image', 'label').text, 'Image position');
    readOnly(slot('default-image', 'label'), imagePlaceholder);
    editable(slot('named-image', 'label'), 'Harbour office');
    readOnly(slot('plain-footer', 'text'), templateLabel);
    editable(slot('slide-footer', 'text'), 'Northwind profile');
    before = await readFile(f.entry, 'utf8');
    assert.equal(await save(f.root, rendered, slot('named-image', 'label'), 'Harbour studio'), before.replace('label="Harbour office"', 'label="Harbour studio"'));
  } finally { await f.cleanup(); }
});
