import test from 'node:test';
import assert from 'node:assert/strict';
import { cp, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { renderOnce } from '../src/server/render';
import { createFromTemplate } from '../src/server/templates';
import { TextEditService } from '../src/server/edits';
import { canCorrectComponent } from '../src/app/componentCorrection';
import type { TextTarget } from '../src/shared/selection';
import type { RenderArtifact } from '../src/shared/types';
import { fixture, projectRoot } from './helpers';

const capitals = /The theme sets this label in capitals/;
const templateLabel = /This label is generated by the template/;
const imagePlaceholder = /This placeholder is generated by the template. Ask your agent to add an image/;
const templateText = /This text is generated by the template/;
const decoration = /This part is generated by the component that draws it/;

async function templatesFixture() {
  const f = await fixture();
  await cp(resolve(projectRoot, 'templates'), resolve(f.root, 'templates'), { recursive: true });
  return f;
}

/** A synthetic document; `capitals` gives the theme capitalised eyebrows and running headers. */
const document = (imports: string, body: string, options: { capitals?: boolean } = {}) => `${imports}
import { neutral } from '../../themes';
const theme = ${options.capitals ? `{ ...neutral, runningHeader: true, design: { title: { uppercaseEyebrow: true }, furniture: { uppercaseHeader: true } } }` : 'neutral'};
export const meta = { title: 'Template labels', description: 'Synthetic template label fixture', theme: 'neutral' };
export default function Proof() { return ${body}; }`;

function targetsOf(artifact: RenderArtifact) {
  const targets = artifact.textTargets ?? [];
  const slot = (blockId: string, name: string) => {
    const found = targets.find(target => target.blockId === blockId && target.slot === name);
    assert.ok(found, `${blockId} ${name}`);
    return found;
  };
  /** A block's only text target, whatever its slot is named. */
  const only = (blockId: string) => {
    const found = targets.filter(target => target.blockId === blockId);
    assert.equal(found.length, 1, blockId);
    return found[0];
  };
  return { targets, slot, only };
}
function editable(target: TextTarget, value: string) {
  assert.ok(canCorrectComponent(target), `${target.id} is editable`);
  const binding = target.runs.find(run => run.source)!.source!;
  assert.equal(binding.file, 'documents/proof/index.tsx', `${target.id} saves to the document's call site`);
  assert.equal(binding.value, value);
}
function readOnly(target: TextTarget, reason: RegExp) {
  assert.equal(canCorrectComponent(target), false, `${target.id} stays read-only`);
  assert.match(target.reason!, reason, target.id);
}
/** Each run's text, with its bound value when editable or else the first sentence of its reason. */
const runs = (target: TextTarget) => target.runs.map(run => [target.text.slice(run.start, run.end), run.source ? `= ${run.source.value}` : run.reason!.split('. ')[0]]);

/** Replace a whole target's text through the reader's save path and return the saved source. */
async function save(root: string, artifact: RenderArtifact, target: TextTarget, replacement: string) {
  await new TextEditService(root).apply('proof', { targetId: target.id, start: 0, end: target.text.length, replacement, revision: 1, hash: artifact.hash }, { id: 'proof', status: 'ready', revision: 1, artifact });
  return readFile(resolve(root, 'documents/proof/index.tsx'), 'utf8');
}

test('report and brief labels edit at the call site, and say so when the theme capitalises them', async () => {
  const f = await templatesFixture();
  try {
    const report = (capitalsTheme: boolean) => document(`import { ConsultingReport } from '../../templates/consulting-report';`,
      `<ConsultingReport title="Quarterly operations" theme={theme} cover={false} label="Operations review" runningTitle="Operations"><></></ConsultingReport>`, { capitals: capitalsTheme });
    await writeFile(f.entry, report(true));
    let rendered = (await renderOnce(f.root, 'proof')).artifact;
    let { slot } = targetsOf(rendered);
    assert.equal(slot('report-label', 'label').text, 'OPERATIONS REVIEW');
    readOnly(slot('report-label', 'label'), capitals);

    await writeFile(f.entry, report(false));
    rendered = (await renderOnce(f.root, 'proof')).artifact;
    ({ slot } = targetsOf(rendered));
    editable(slot('report-label', 'label'), 'Operations review');
    const before = await readFile(f.entry, 'utf8');
    assert.equal(await save(f.root, rendered, slot('report-label', 'label'), 'Operations audit'), before.replace('label="Operations review"', 'label="Operations audit"'));

    const brief = (capitalsTheme: boolean) => document(`import { ExecutiveBrief } from '../../templates/executive-brief';`,
      `<ExecutiveBrief title="Brief" theme={theme} label="Board update" author="Strategy team" date="May 2026"><></></ExecutiveBrief>`, { capitals: capitalsTheme });
    await writeFile(f.entry, brief(true));
    rendered = (await renderOnce(f.root, 'proof')).artifact;
    ({ slot } = targetsOf(rendered));
    assert.equal(slot('brief-label', 'label').text, 'BOARD UPDATE');
    readOnly(slot('brief-label', 'label'), capitals);

    await writeFile(f.entry, brief(false));
    rendered = (await renderOnce(f.root, 'proof')).artifact;
    ({ slot } = targetsOf(rendered));
    editable(slot('brief-label', 'label'), 'Board update');
    const details = slot('brief-details', 'author');
    assert.deepEqual(details.runs.map(run => [details.text.slice(run.start, run.end), run.source?.value ?? run.reason?.split('.')[0]]),
      [['Strategy team', 'Strategy team'], [' · ', 'This part is generated by the component that draws it'], ['May 2026', 'May 2026']]);
  } finally { await f.cleanup(); }
});

test('image-story and company-profile defaults explain themselves, and supplied labels edit at the call site', async () => {
  const f = await templatesFixture();
  try {
    await writeFile(f.entry, document(`import { ImageStory, ImageStoryPage } from '../../templates/image-story';`,
      `<ImageStory title="Story" theme={theme}><ImageStoryPage id="first" theme={theme} title="First page" /><ImageStoryPage id="second" theme={theme} title="Second page" footer="Field notes" /></ImageStory>`));
    let rendered = (await renderOnce(f.root, 'proof')).artifact;
    assert.deepEqual(rendered.issues, []);
    let { slot } = targetsOf(rendered);
    assert.equal(slot('first-footer', 'footer').text, 'IMAGE STORY');
    readOnly(slot('first-footer', 'footer'), templateLabel);
    readOnly(slot('first-image', 'placeholder'), imagePlaceholder);
    editable(slot('second-footer', 'footer'), 'Field notes');
    let before = await readFile(f.entry, 'utf8');
    assert.equal(await save(f.root, rendered, slot('second-footer', 'footer'), 'Site notes'), before.replace('footer="Field notes"', 'footer="Site notes"'));

    const manifestFile = resolve(f.root, 'projects.json');
    await writeFile(manifestFile, JSON.stringify({ ...JSON.parse(await readFile(manifestFile, 'utf8')), formats: { proof: 'presentation' } }));
    await writeFile(f.entry, document(`import { CompanyProfile, ProfileImage, ProfileSlide } from '../../templates/company-profile';`,
      `<CompanyProfile title="Profile" theme={theme}><ProfileSlide id="slide" theme={theme} title="Places" footer="Northwind profile">
        <ProfileImage id="default-image" theme={theme} x={40} y={200} width={300} height={200} />
        <ProfileImage id="named-image" theme={theme} x={400} y={200} width={300} height={200} label="Harbour office" />
      </ProfileSlide><ProfileSlide id="plain" theme={theme} title="Plain" /></CompanyProfile>`));
    rendered = (await renderOnce(f.root, 'proof')).artifact;
    ({ slot } = targetsOf(rendered));
    assert.equal(slot('default-image', 'label').text, 'Image position');
    readOnly(slot('default-image', 'label'), imagePlaceholder);
    editable(slot('named-image', 'label'), 'Harbour office');
    readOnly(slot('plain-footer', 'text'), templateLabel);
    editable(slot('slide-footer', 'text'), 'Northwind profile');
    before = await readFile(f.entry, 'utf8');
    assert.equal(await save(f.root, rendered, slot('named-image', 'label'), 'Harbour studio'), before.replace('label="Harbour office"', 'label="Harbour studio"'));
  } finally { await f.cleanup(); }
});

test('business templates explain their labels, prefixes, and separators while supplied text stays editable', async () => {
  const f = await templatesFixture();
  try {
    await writeFile(f.entry, document(`import { BusinessProposal } from '../../templates/business-proposal';`,
      `<BusinessProposal title="Fit-out proposal" theme={theme} preparedFor="Harbour Trust" preparedBy="Studio North" date="May 2026" reference="P-104" acceptance="Sign to accept."><></></BusinessProposal>`));
    const rendered = (await renderOnce(f.root, 'proof')).artifact;
    const { slot, only } = targetsOf(rendered);
    readOnly(slot('proposal-label', 'children'), templateLabel);
    assert.deepEqual(runs(only('proposal-client')), [['Prepared for ', 'This label is generated by the template'], ['Harbour Trust', '= Harbour Trust']]);
    assert.deepEqual(runs(slot('proposal-reference', 'date')), [['May 2026', '= May 2026'], [' · ', 'This part is generated by the component that draws it'], ['P-104', '= P-104']]);
    assert.deepEqual(runs(only('proposal-acceptance')), [['Acceptance. ', 'This label is generated by the template'], ['Sign to accept.', '= Sign to accept.']]);
    const before = await readFile(f.entry, 'utf8');
    const client = only('proposal-client');
    await new TextEditService(f.root).apply('proof', { targetId: client.id, start: 13, end: client.text.length, replacement: 'Harbour Council', revision: 1, hash: rendered.hash }, { id: 'proof', status: 'ready', revision: 1, artifact: rendered });
    assert.equal(await readFile(f.entry, 'utf8'), before.replace('preparedFor="Harbour Trust"', 'preparedFor="Harbour Council"'), 'The prefix stays fixed and the supplied name saves at the call site');

    for (const template of ['invoice', 'quotation']) {
      const created = await createFromTemplate(f.root, template, { projectId: 'test-project', id: `labels-${template}`, title: 'Label proof', theme: 'neutral' });
      const data = JSON.parse(await readFile(resolve(f.root, 'documents', created.id, 'data.json'), 'utf8'));
      const instance = targetsOf((await renderOnce(f.root, created.id)).artifact);
      const prefix = template === 'invoice' ? 'invoice' : 'quote';
      readOnly(instance.slot(`${prefix}-label`, 'children'), templateLabel);
      readOnly(instance.slot(`${prefix}-sample-notice`, 'children'), templateText);
      const number = runs(instance.slot(template === 'invoice' ? 'invoice-number' : 'quote-reference', 'number'));
      assert.deepEqual(number.slice(0, 2), [['No. ', 'This label is generated by the template'], [data.number, `= ${data.number}`]], template);
      assert.ok(number.slice(2).every(([text, value]) => text.startsWith(' · ') ? /generated by the template/.test(value) : value.startsWith('= ')), `${template}: date and reference prefixes are template labels`);
      assert.deepEqual(runs(instance.slot('pricing-totals', 'tax-label')), [[data.pricing.tax.label, `= ${data.pricing.tax.label}`], [' (', 'This part is generated by the component that draws it'], [String(data.pricing.tax.ratePercent), 'Calculated input—ask your agent to change the tax rate.'], ['%)', 'This part is generated by the component that draws it']]);
      const item = data.pricing.items.find((entry: { unit?: string }) => entry.unit);
      const quantity = runs(instance.targets.find(target => target.slot === `item-${item.id.length}-${item.id}-quantity-unit`)!);
      assert.deepEqual(quantity.slice(1), [[' ', 'This part is generated by the component that draws it'], [item.unit, `= ${item.unit}`]]);
      if (template === 'invoice') {
        readOnly(instance.slot('invoice-balance-summary', 'amount-due-label'), templateLabel);
        assert.equal(runs(instance.slot('invoice-balance-summary', 'dueOn'))[0][1], 'This label is generated by the template');
        assert.equal(runs(instance.only('invoice-payment-reference'))[0][1], 'This label is generated by the template');
      } else assert.equal(runs(instance.only('quote-acceptance'))[0][1], 'This label is generated by the template');
    }
  } finally { await f.cleanup(); }
});

test('report, paper, scene, and slide furniture say why the template owns them', async () => {
  const f = await templatesFixture();
  try {
    const created = await createFromTemplate(f.root, 'monthly-report', { projectId: 'test-project', id: 'labels-monthly', title: 'Label proof' });
    const file = resolve(f.root, 'documents', created.id, 'data.json');
    const data = JSON.parse(await readFile(file, 'utf8'));
    delete data.metrics[0].note;
    await writeFile(file, JSON.stringify(data, null, 2));
    const monthly = targetsOf((await renderOnce(f.root, created.id)).artifact);
    readOnly(monthly.slot('report-title-subtitle', 'subtitle'), /Formatted dates/);
    assert.deepEqual(runs(monthly.slot('report-title-byline', 'byline')).map(([, value]) => value.startsWith('= ') ? 'bound' : value),
      ['bound', 'This label is generated by the template', 'bound', 'This label is generated by the template', 'Formatted date']);
    readOnly(monthly.slot('sample-notice', 'children'), templateText);
    readOnly(monthly.slot('summary-heading', 'title'), templateLabel);
    for (const heading of ['highlights-heading', 'risks-heading', 'notes-heading']) readOnly(monthly.slot(heading, 'children'), templateLabel);
    const risk = data.risks[0];
    const level = runs(monthly.slot(`risk-${risk.id.length}-${risk.id}-heading`, 'title'));
    assert.deepEqual(level.slice(0, 2), [[risk.title, `= ${risk.title}`], [' / ', 'This part is generated by the component that draws it']]);
    assert.ok(level.slice(2).length && level.slice(2).every(([, value]) => value === 'Reported level'), 'The capitalised level explains itself');
    assert.deepEqual(runs(monthly.only(`risk-${risk.id.length}-${risk.id}-owner`)), [['Owner: ', 'This label is generated by the template'], [risk.owner, `= ${risk.owner}`]]);
    assert.equal(runs(monthly.only('source-note'))[0][1], 'This label is generated by the template');
    const metric = data.metrics[0];
    readOnly(monthly.slot('performance-table', `metric-${metric.id.length}-${metric.id}-note`), /No context is given for this measure/);

    await writeFile(f.entry, document(`import { ScientificPaper } from '../../templates/scientific-paper';
import { SceneBreak } from '../../templates/literary-text';`,
      `<ScientificPaper title="Paper" theme={theme} abstract="We measured it." keywords="flow, reading"><SceneBreak id="scene" lead="The scene opens." /></ScientificPaper>`));
    const paper = targetsOf((await renderOnce(f.root, 'proof')).artifact);
    assert.deepEqual(runs(paper.only('paper-abstract')), [['Abstract. ', 'This label is generated by the template'], ['We measured it.', '= We measured it.']]);
    assert.deepEqual(runs(paper.only('paper-keywords')), [['Keywords: ', 'This label is generated by the template'], ['flow, reading', '= flow, reading']]);
    readOnly(paper.slot('scene-marker', 'children'), decoration);
    editable(paper.slot('scene-lead', 'lead'), 'The scene opens.');

    const deck = await createFromTemplate(f.root, 'pitch-deck', { projectId: 'test-project', id: 'labels-pitch', title: 'Label proof', theme: 'neutral' });
    const pitch = (await renderOnce(f.root, deck.id)).artifact.textTargets ?? [];
    const numbers = pitch.filter(target => target.text === '{{pageNumber}}');
    assert.ok(numbers.length, 'Slides carry page numbers');
    for (const target of numbers) readOnly(target, decoration);
  } finally { await f.cleanup(); }
});
