import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { renderOnce } from '../src/server/render';
import { TextEditService } from '../src/server/edits';
import { canCorrectComponent, componentCorrection } from '../src/app/componentCorrection';
import type { TextTarget } from '../src/shared/selection';
import { fixture } from './helpers';

const document = (body: string) => `import { Document, Pages, Block } from '../../src/document';
import { theme } from '../../themes/field-manual';
import { DirectivePage, EvidenceChain, ManualCode, ManualOpening, ManualPages, SpecRows } from '../../themes/field-manual/components';
import { ExhibitTitle, Implication, RankedBars } from '../../themes/mckinsey-consulting/components';
import { CivicBadge, SquareSignal } from '../../themes/civic-spectrum/components';
export const meta = { title: 'Theme labels', description: 'Synthetic theme label fixture', theme: theme.id };
export default function Proof() { return <Document title={meta.title} theme={theme}>${body}</Document>; }`;

test('theme components bind the labels a document writes and explain the ones the theme draws', async () => {
  const f = await fixture();
  try {
    await writeFile(f.entry, document(`<ManualPages title="Theme labels">
      <ManualOpening id="opening" code="FM-02" label="Decision anatomy" title="A decision should expose its chain." />
      <ManualCode id="code" code="CLR" label="Signal / support" />
      <EvidenceChain id="chain" steps={[{ title: 'Source', detail: 'Name the record.' }, { title: 'Reason', detail: 'Show the rule.' }, { title: 'Act', detail: 'State the result.' }]} />
      <SpecRows id="record" rows={[{ label: 'Class', value: 'Reference' }, { label: 'Mode', value: 'Reference' }]} />
      <Block id="exhibit"><ExhibitTitle id="exhibit-title" number="01" topic="Visual grammar" metric="Points, illustrative">Structure stays quiet.</ExhibitTitle></Block>
      <RankedBars id="bars" max={40} rows={[{ label: 'Simplify intake', value: 32 }, { label: 'Balance capacity', value: 28 }]} />
      <Implication id="implication">Validate the largest levers first.</Implication>
      <Implication id="named-implication" label="Next step">Fund the pilot.</Implication>
      <SquareSignal id="signal" label="Community brief" />
      <CivicBadge id="badge" value="01" label="One system." />
    </ManualPages>
    <DirectivePage id="directive" code="FM-03" revision="REV 01" title="Document what changes." lead="Leave a path back to each reason." rows={[{ label: 'Change', value: 'State what changed.' }]} />`));
    const artifact = (await renderOnce(f.root, 'proof')).artifact;
    const targets = artifact.textTargets!;
    const slot = (blockId: string, name: string) => {
      const found = targets.find(target => target.blockId === blockId && target.slot === name);
      assert.ok(found, `${blockId} ${name}`);
      return found;
    };
    const editable = (target: TextTarget, value: string) => {
      assert.ok(canCorrectComponent(target), `${target.id} is editable`);
      const binding = target.runs.find(run => run.source)!.source!;
      assert.equal(binding.file, 'documents/proof/index.tsx', `${target.id} saves to the document's call site`);
      assert.equal(binding.value, value);
    };
    const readOnly = (target: TextTarget, reason: RegExp) => {
      assert.equal(canCorrectComponent(target), false, `${target.id} stays read-only`);
      assert.match(target.reason!, reason, target.id);
    };

    // Field Manual: literal props are editable where the document writes them, through nested compositions too.
    editable(slot('opening-code', 'code'), 'FM-02');
    editable(slot('opening-title', 'title'), 'A decision should expose its chain.');
    editable(slot('code', 'code'), 'CLR');
    readOnly(slot('opening-code', 'label'), /The theme sets this label in capitals/);
    readOnly(slot('chain', 'input-label'), /This label is generated by the theme/);
    editable(slot('chain', 'method-title'), 'Reason');
    editable(slot('chain', 'output-detail'), 'State the result.');
    assert.ok(targets.every(target => target.text !== '→'), 'The arrow between steps is a decoration, not a text target');
    readOnly(slot('record', 'row-1-label'), /capitals/);
    readOnly(slot('record', 'row-1-value'), /cannot be traced|generated by the document's code/);
    readOnly(slot('directive-note', 'code'), /This text is part of the theme/);
    editable(slot('directive-code', 'code'), 'REV 01');
    editable(slot('directive-record', 'row-1-value'), 'State what changed.');
    editable(slot('directive-lead', 'lead'), 'Leave a path back to each reason.');

    // McKinsey Consulting: a composed label keeps its generated parts fixed and its written part editable.
    const exhibit = targets.find(target => target.blockId === 'exhibit')!;
    assert.equal(exhibit.text, 'EXHIBIT 01 / VISUAL GRAMMAR');
    assert.deepEqual(exhibit.runs.map(run => [exhibit.text.slice(run.start, run.end), !!run.source]), [['EXHIBIT ', false], ['01', true], [' / ', false], ['VISUAL GRAMMAR', false]]);
    assert.deepEqual(componentCorrection(exhibit, 'EXHIBIT 02 / VISUAL GRAMMAR'), { start: 8, end: 10, replacement: '02' });
    assert.equal(componentCorrection(exhibit, 'FIGURE 01 / VISUAL GRAMMAR'), undefined, 'The generated prefix cannot be edited');
    editable(slot('exhibit-title-claim', 'children'), 'Structure stays quiet.');
    editable(slot('exhibit-title-metric', 'metric'), 'Points, illustrative');
    editable(slot('bars', 'row-2-label'), 'Balance capacity');
    readOnly(slot('bars', 'row-1-value'), /generated by the theme from the chart's data/);
    readOnly(slot('implication', 'label'), /This label is generated by the theme/);
    editable(slot('named-implication', 'label'), 'Next step');
    editable(slot('implication', 'children'), 'Validate the largest levers first.');

    // Civic Spectrum.
    readOnly(slot('signal', 'label'), /capitals/);
    editable(slot('badge', 'value'), '01');
    editable(slot('badge', 'label'), 'One system.');

    const service = new TextEditService(f.root);
    const before = await readFile(f.entry, 'utf8');
    const code = slot('opening-code', 'code');
    await service.apply('proof', { targetId: code.id, start: 0, end: code.text.length, replacement: 'FM-09', revision: 1, hash: artifact.hash }, { id: 'proof', status: 'ready', revision: 1, artifact });
    const saved = await readFile(f.entry, 'utf8');
    assert.equal(saved, before.replace('code="FM-02"', 'code={"FM-09"}'));
    const next = (await renderOnce(f.root, 'proof')).artifact;
    const title = next.textTargets!.find(target => target.blockId === 'chain' && target.slot === 'method-title')!;
    await service.apply('proof', { targetId: title.id, start: 0, end: title.text.length, replacement: 'Rule', revision: 2, hash: next.hash }, { id: 'proof', status: 'ready', revision: 2, artifact: next });
    assert.equal(await readFile(f.entry, 'utf8'), saved.replace(`{ title: 'Reason', detail`, `{ title: "Rule", detail`));
  } finally { await f.cleanup(); }
});

test('TextSlot and Decoration bind and describe text without changing the PDF', async () => {
  const f = await fixture();
  const page = (body: string) => `import { Document, Pages, Block, TextSlot, Decoration, View, Text } from '../../src/document';
export const meta = { title: 'Transparent', description: 'Synthetic transparency fixture', theme: 'neutral' };
function Label({ number, topic }: { number: string; topic: string }) { return ${body}; }
export default function Proof() { return <Document title={meta.title}><Pages title="Transparent"><Block id="label"><Label number="01" topic="Grammar" /></Block></Pages></Document>; }`;
  try {
    await writeFile(f.entry, page(`<View><Text>→</Text><Text>EXHIBIT {number} / {topic.toUpperCase()}</Text></View>`));
    const plain = (await renderOnce(f.root, 'proof')).artifact;
    await writeFile(f.entry, page(`<View><Decoration><Text>→</Text></Decoration><Text><Decoration>EXHIBIT </Decoration><TextSlot slot="number" from="number">{number}</TextSlot><Decoration> / </Decoration><TextSlot slot="topic" reason="Capitals.">{topic.toUpperCase()}</TextSlot></Text></View>`));
    const bound = (await renderOnce(f.root, 'proof')).artifact;
    assert.equal(bound.hash, plain.hash, 'The PDF bytes are identical');
    assert.deepEqual(plain.textTargets!.map(target => target.text), ['→', 'EXHIBIT 01 / GRAMMAR']);
    assert.deepEqual(bound.textTargets!.map(target => target.text), ['EXHIBIT 01 / GRAMMAR'], 'A decoration drawn as its own text is not a target');
    assert.ok(bound.textTargets![0].lines.length, 'Text with inline decorations keeps its PDF geometry');
  } finally { await f.cleanup(); }
});
