/** Source values are issued by the renderer. Clients never choose a file to edit. */
export type { TextEditPreview } from './types';
export interface TextSourceValue {
  /** Identity of the authored token; draft previews retain their original binding. */
  bindingId?: string;
  file: string;
  digest: string;
  start: number;
  end: number;
  /** `number` is a numeric literal, such as a DataTable cell; `value` is its displayed text. */
  kind: 'jsx-text' | 'jsx-attribute' | 'string' | 'json-string' | 'number';
  value: string;
  linkedOccurrences?: number;
}

/** Shown when the renderer cannot prove which authored value produced a text run. */
export const generatedTextReason = "This text is generated by the document's code. Ask your agent to make it editable, or comment instead.";
/** Shown when the text is placed by a theme, template, or other shared file, whose source is never edited from a document. */
export const sharedTextReason = (file: string) => `This text is placed by ${file}, which does not link it to this document's source. Ask your agent to change it there or make it editable, or comment instead.`;

/** Shown when a correction to a numeric literal is not a plain number. */
export const numberSourceError = 'This cell holds a number. Enter it as plain digits, such as 1250, -3, or 12.5: no commas, spaces, units, or trailing zeros.';
/**
 * Whether text can replace a numeric literal and display exactly as typed: a finite number in
 * the form the renderer writes it, so the saved cell shows the same characters.
 */
export function numberSourceText(text: string) {
  return Number.isFinite(Number(text)) && String(Number(text)) === text;
}

export interface TextRun {
  start: number;
  end: number;
  source?: TextSourceValue;
  protected?: boolean;
  reason?: string;
}

export interface TextLine {
  page: number;
  x: number;
  y: number;
  width: number;
  height: number;
  text: string;
  start: number;
  end: number;
}

/** A stable content slot within a block, independent of its current page. */
export interface TextTarget {
  id: string;
  blockId: string;
  slot: string;
  /** Anonymous positional slots support revision-checked edits, not durable phrase anchors. */
  stable?: boolean;
  text: string;
  runs: TextRun[];
  lines: TextLine[];
  reason?: string;
}

export interface DocumentSelection {
  blockId: string;
  targetId?: string;
  start?: number;
  end?: number;
  quote?: string;
  page: number;
  renderHash?: string;
  revision?: number;
}

export interface TextAnchor {
  targetId: string;
  start: number;
  end: number;
  quote: string;
  prefix: string;
  suffix: string;
}

export interface ManualEditSummary {
  id: string;
  blockId: string;
  targetId: string;
  before: string;
  after: string;
  at: string;
  canUndo: boolean;
  count?: number;
}

export interface TextEditChange {
  targetId: string;
  start: number;
  end: number;
  replacement: string;
}

export interface TextEditInput extends TextEditChange {
  revision: number;
  hash: string;
}

export interface TextEditBatchInput {
  revision: number;
  hash: string;
  edits: TextEditChange[];
}
